language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

cache: pip

addons:
  postgresql: 9.6

install: 'pip install -r requirements-dev.txt'

script:
  - flake8
  - pytest -ra -vvv --cov

after_success: codecov
