[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"
addopts = "-m \"not integration_test\""
markers = [
    "custom_ds: integration tests for custom data source",
    "custom_pk_ds: integration tests for custom primary key data source",
    "integration_test: integration tests"
]

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I",
    # pep8-naming
    "N",
    # flake8-bugbear without opinionated rules
    "B0",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
]
extend-per-file-ignores = { "**/migrations/*" = ["E501"], "**/tests/*" = ["E501"] }
