sonar.projectKey=City-of-Helsinki_django-orghierarchy
sonar.organization=city-of-helsinki
sonar.python.version=3.10
sonar.python.coverage.reportPaths=.coverage-reports/coverage-3.10.xml
sonar.test.inclusions=**/tests/**/*
sonar.exclusions=**/migrations/*,pipelines/**/*
