# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='responsible_organization',
            field=models.ForeignKey(blank=True, help_text='Responsible organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_organization', to='django_orghierarchy.Organization'),
        ),
    ]
