# Generated by Django 2.1.7 on 2019-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0008_set_on_delete_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='distinct_name',
            field=models.CharField(editable=False, help_text='A distinct name for this organization (generated automatically)', max_length=400, null=True),
        ),
    ]
