# Generated by Django 3.1.5 on 2021-02-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0009_add_organization_distinct_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('add_affiliated_organization', 'Can add affiliated organization'), ('change_affiliated_organization', 'Can change affiliated organization'), ('delete_affiliated_organization', 'Can delete affiliated organization'), ('replace_organization', 'Can replace an organization with a new one')), 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
