# Generated by Django 3.2 on 2023-02-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdatasource',
            name='user_editable_organizations',
            field=models.BooleanField(default=False, verbose_name='Organizations may be edited by users'),
        ),
    ]
