name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    uses: City-of-Helsinki/.github/.github/workflows/ci-python-library.yml@main
    with:
      python-matrix: "['3.10', '3.11', '3.12', '3.13', '3.14']"
      python-version: "3.10"
      commitlint-config-file: "./.commitlintrc.mjs"
      enable-sonar: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build package
    uses: City-of-Helsinki/.github/.github/workflows/build-python-dists.yml@main
    with:
      python-version: "3.10"
