name: Continuous integration

env:
  DEFAULT_PYTHON: 3.9

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Enable manual run
  workflow_dispatch:

jobs:
  test:
    name: Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    env:
      TOX_POSARGS: -- --cov=. --cov-report=xml -ra -vv
    strategy:
      matrix:
        python_version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: pip

      - name: Upgrade packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: python -m pip install --upgrade codecov tox

      - name: Run tox targets for Python ${{ matrix.python_version }}
        run: tox run -f py$(echo ${{ matrix.python_version }} | tr -d .) ${{ env.TOX_POSARGS }}

      - name: Upload Coverage to Codecov
        if: ${{ matrix.python_version == env.DEFAULT_PYTHON }}
        uses: codecov/codecov-action@v3

  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install dependencies
        run: pip install -U setuptools wheel build
      - name: Build
        run: python -m build .

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check commitlint
        uses: wagoid/commitlint-github-action@3d28780bbf0365e29b144e272b2121204d5be5f3  # v6.1.2

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
