name: release-please
on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
      # Build and publish to PyPI
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
        if: ${{ steps.release.outputs.release_created }}
      - name: Install dependencies
        run: pip install -U setuptools wheel build
        if: ${{ steps.release.outputs.release_created }}
      - name: Build
        run: python -m build .
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
        if: ${{ steps.release.outputs.release_created }}
