name: release-please
on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
